<a href="https://colab.research.google.com/github/oumaima61/my-machine-learning-projects/blob/master/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
nltk.download('punkt')
sentence = "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do."

sentence_tokenized = nltk.word_tokenize(sentence)

print (sentence_tokenized)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
['Alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of', 'sitting', 'by', 'her', 'sister', 'on', 'the', 'bank', ',', 'and', 'of', 'having', 'nothing', 'to', 'do', '.']


In [ ]:
paragraph = """
            Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, 
            but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?”
"""

para_tokenized = nltk.word_tokenize(paragraph)

print (para_tokenized) 

['Alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of', 'sitting', 'by', 'her', 'sister', 'on', 'the', 'bank', ',', 'and', 'of', 'having', 'nothing', 'to', 'do', ':', 'once', 'or', 'twice', 'she', 'had', 'peeped', 'into', 'the', 'book', 'her', 'sister', 'was', 'reading', ',', 'but', 'it', 'had', 'no', 'pictures', 'or', 'conversations', 'in', 'it', ',', '“', 'and', 'what', 'is', 'the', 'use', 'of', 'a', 'book', ',', '”', 'thought', 'Alice', '“', 'without', 'pictures', 'or', 'conversations', '?', '”']


In [ ]:
paragraph = """
            As she said this she looked down at her hands, and was surprised to 
            see that she had put on one of the Rabbit’s little white kid gloves while she was talking. “How can I have done that?” she thought. “I must be growing small again.”
"""

para_tokenized = nltk.sent_tokenize(paragraph)

print (para_tokenized)

['\n            As she said this she looked down at her hands, and was surprised to \n            see that she had put on one of the Rabbit’s little white kid gloves while she was talking.', '“How can I have done that?” she thought.', '“I must be growing small again.”']


Normalisation 

In [ ]:
from nltk.corpus import stopwords
#Download stop words from nltk library
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

tokens = nltk.word_tokenize(paragraph)

clean_paragraph = [word for word in tokens if word not in stop_words]

try:
  print ("print tokens ")
  print (clean_paragraph)
except:
  print ("expected variable called clean_sentence") 

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
print tokens 
['As', 'said', 'looked', 'hands', ',', 'surprised', 'see', 'put', 'one', 'Rabbit', '’', 'little', 'white', 'kid', 'gloves', 'talking', '.', '“', 'How', 'I', 'done', '?', '”', 'thought', '.', '“', 'I', 'must', 'growing', 'small', '.', '”']


In [ ]:
sentence = "Wow this is cool ! wow this is awesome."
lit_sentence = sentence.lower()
upp_sentence = sentence.upper()

print (lit_sentence)

print (upp_sentence) 

wow this is cool ! wow this is awesome.
WOW THIS IS COOL ! WOW THIS IS AWESOME.


 Stemming and Lemmatization

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

sentence = "There might be some sense in your knocking."

tokens = word_tokenize(sentence)
word_stemmed = [stemmer.stem(word) for word in tokens]

print ("List of Tokens ")
print (tokens)

print ("\n")
print ("List of stemmed words")
print (word_stemmed)

List of Tokens 
['There', 'might', 'be', 'some', 'sense', 'in', 'your', 'knocking', '.']


List of stemmed words
['there', 'might', 'be', 'some', 'sens', 'in', 'your', 'knock', '.']


In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
nltk.download('wordnet')

Lemmatizer = WordNetLemmatizer()
sentence = "There might be some sense in your knocking."
tokens = word_tokenize(sentence)

lemma = [Lemmatizer.lemmatize(token) for token in tokens]

print (lemma) 

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
['There', 'might', 'be', 'some', 'sense', 'in', 'your', 'knocking', '.']


Bag-of-Words

In [ ]:
corpus = ["Emma was a Catholic because her mother was a Catholic, and Nory’s mother was a Catholic because her father was a Catholic, and her father was a Catholic because his mother was a Catholic, or had been."]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus_vectorizer = CountVectorizer()
corpus_vectorizer.fit(corpus) 

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [ ]:
#show count for each word present in corpus
corpus_vectorizer.vocabulary_

{'and': 0,
 'because': 1,
 'been': 2,
 'catholic': 3,
 'emma': 4,
 'father': 5,
 'had': 6,
 'her': 7,
 'his': 8,
 'mother': 9,
 'nory': 10,
 'or': 11,
 'was': 12}

In [ ]:
corpus = "Emma was a Catholic because her mother was a Catholic, and Nory’s mother was a Catholic because her father was a Catholic, and her father was a Catholic because his mother was a Catholic, or had been."

In [ ]:
#Python code without any nlp library
tokens = corpus.split()
#Uncomment to see all the tokens
#print (tokens)
#define empty dictionary 
dic = {}

#save frequency of each token in dictiory
for token in tokens:
  count = 1
  if token not in dic:
    dic[token] = count
  else:
    dic[token] = dic[token] + 1

print (dic) 

{'Emma': 1, 'was': 6, 'a': 6, 'Catholic': 3, 'because': 3, 'her': 3, 'mother': 3, 'Catholic,': 3, 'and': 2, 'Nory’s': 1, 'father': 2, 'his': 1, 'or': 1, 'had': 1, 'been.': 1}


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [ ]:
doc_1 = "She is cute"
doc_2 = "He is very cute"
doc_3 = "Angelina is very very cute"

corpus = [doc_1, doc_2, doc_3]

corpus_preprocess = []

for doc in corpus:
  corpus_preprocess.append(doc.lower())

corpus_vectorizer = TfidfVectorizer(norm=None)
tf_idf_scores = corpus_vectorizer.fit_transform(corpus_preprocess)

feature_names = corpus_vectorizer.get_feature_names()
corpus_index = [doc for doc in corpus_preprocess]

print ("TF-IDF table of corpus")
print ("======================\n")

print(pd.DataFrame(tf_idf_scores.T.todense(), index = feature_names, columns = ["doc_1", "doc_2", "doc_3"]))

TF-IDF table of corpus

             doc_1     doc_2     doc_3
angelina  0.000000  0.000000  1.693147
cute      1.000000  1.000000  1.000000
he        0.000000  1.693147  0.000000
is        1.000000  1.000000  1.000000
she       1.693147  0.000000  0.000000
very      0.000000  1.287682  2.575364


Internally, `CountVectorizer` and `TfidfTransformer` are used to calculate term frequency and inverse document frequency in `TfidfVectorizer`. For a better understanding, a breakdown is given below. 

In [ ]:
#Part 1 - Calculating Term Frequencies
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
term_frequency = vectorizer.fit_transform(corpus_preprocess)

#uncomment following to check feature names
#print(vectorizer.get_feature_names())

print ("Term Frequency Matrix")
print ("=====================")
print (term_frequency.toarray())
print ("=====================")
#Part 2 - Calculating Inverse Document Frequency
from sklearn.feature_extraction.text import TfidfTransformer

vectorizer = TfidfTransformer(norm=None)
vectorizer.fit(term_frequency)

idf = vectorizer.idf_

df = pd.DataFrame(idf, index = feature_names, columns=['IDF'])
print ("\nIDF table")
print ("=========")
print(df)


tf_idf_scores = vectorizer.fit_transform(term_frequency.toarray())


print ("\nTF-IDF matrix")
print ("=============\n")
print (tf_idf_scores.toarray())

Term Frequency Matrix
[[0 1 0 1 1 0]
 [0 1 1 1 0 1]
 [1 1 0 1 0 2]]

IDF table
               IDF
angelina  1.693147
cute      1.000000
he        1.693147
is        1.000000
she       1.693147
very      1.287682

TF-IDF matrix

[[0.         1.         0.         1.         1.69314718 0.        ]
 [0.         1.         1.69314718 1.         0.         1.28768207]
 [1.69314718 1.         0.         1.         0.         2.57536414]]
